### ISSUE TITLE
Add ability to reference environment or composition for input values

### ISSUE THREAD

**Issue by djeremiah** [djeremiah/function-cidrsubnet#1]
Something like
```yaml
  - step: generate-subnet
    functionRef:
      name: function-cidrsubnet
    input:
      apiVersion: cidrsubnet.fn.crossplane.io/v1beta1
      kind: Input
      metadata:
        name: subnet-a
      prefix: ${environment.networkCIDR}
      newbits: 4
      netnum: 15
```
